## Loss or Cost function 

In [1]:
import numpy as np

In [2]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.3, 0.7, 1, 0, 0.5]) # target output between 0 to 1

In [3]:
# define a function for various errors 
# mean absolute error = 1/n (sum (abs(y_true- y_predicted)))
# mean square error = 1/n(sum (y_true-y_predicted)**2)
# Binary cross entropy or Log loss = -1/n (sum(y_true(i)*log(y_predicted(i) + (1-y_true(i) * (log(1-y_pridicted(i)))))))

In [4]:
def mae(y_true, y_predicted):
    total_error = 0
    for yt, yp in zip (y_true, y_predicted): 
        total_error = total_error+abs(yt-yp)
    print("Total error", total_error)
        
    mae = total_error / len(y_true)
    print("Mean Abs Error : ", mae)
    return mae

In [5]:
mae(y_true, y_predicted)

Total error 2.5
Mean Abs Error :  0.5


0.5

In [6]:
# alternatively use numpy to find mean
np.mean(np.array(abs(y_predicted-y_true)))

0.5

In [7]:
np.sum(np.array(abs(y_predicted-y_true)))

2.5

In [8]:
# define mean square error using python 
def mse(y_true, y_predicted):
    total_error = 0
    for yt, yp in zip (y_true, y_predicted): 
        total_error = total_error+(yt-yp)**2
    print("Total error", total_error)
        
    mse = total_error / len(y_true)
    print("Mean Square Error : ", mse)
    return mse

In [9]:
mse(y_true, y_predicted)

Total error 1.83
Mean Square Error :  0.366


0.366

In [10]:
# alternatively use numpy to find mean square error
np.mean(np.array((y_predicted-y_true)**2))

0.366

In [11]:
np.sum(np.array((y_predicted-y_true)**2))

1.83

In [12]:
np.log([0])

<ipython-input-12-faee82fd9f21>:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [13]:
np.log([0.00000000001])

array([-25.32843602])

In [14]:
# define log loss function (or binary cross entropy function)

# log (0) is infinity, hence in the function , whenever y predicted is zero or 1 ,
# log y_predicted or log(1-y_predicted) would cause problem in the programm, 
# hence need to define log function close to zero (0.000000000001 to say) ) 

In [15]:
# define epsilon function
eplison = 1e-15

In [16]:
y_predicted

array([1, 1, 0, 0, 1])

In [17]:
# in y predited values, replace all 1 with a value close to 1 i.e 0.99999999999 and 0 with a value close to zero i.e 0.00000000000001)
y_predicted_new = [max (i, eplison) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [18]:
# it can be see above output that replaced all zero with close to zero values, similarly replace all 1 with a value close to 1
y_predicted_new = [min (i, 1-eplison) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [19]:
# convert into numpy array 
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [20]:
np.log(y_predicted)

<ipython-input-20-d8d657355a01>:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted)


array([  0.,   0., -inf, -inf,   0.])

In [21]:
# define log loss function
-np.mean(y_true * np.log(y_predicted_new)+(1-y_true) * np.log(1-y_predicted_new))

17.2696280766844

In [22]:
# define function 
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i, eplison) for i in y_predicted]
    y_predicted_new = [min(i, 1-eplison) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true * np.log(y_predicted_new)+(1-y_true) * np.log(1-y_predicted_new))

In [23]:
log_loss(y_true, y_predicted)

17.2696280766844